import streamlit as st
import requests
import json

# Streamlit UI
st.title("🎥 AI Quiz Maker")
st.markdown("Enter a YouTube link below and get a quiz generated by AI!")

# User input
youtube_url = st.text_input("YouTube Video URL")

if st.button("Generate Quiz"):
    if youtube_url:
        with st.spinner("Processing..."):
            try:
                # Send request to FastAPI backend
                response = requests.get(
                    "http://localhost:8000/generate-quiz/",
                    params={"url": youtube_url},
                    timeout=120
                )

                if response.status_code == 200:

                    quiz = response.json().get("quiz", "No quiz found.")
                    st.success("Quiz generated successfully!")
                    st.json(quiz)
                else:
                    st.error(f"Error from backend: {response.status_code}")
                    st.text(response.text)

            except requests.exceptions.RequestException as e:

                st.error(f"Request failed: {e}")
    else:
        st.warning("Please enter a valid YouTube URL.")
